image: gitpod/workspace-base

tasks:
- name: install mamba, get data
  init: |
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh

    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n annotation -c bioconda star scallop salmon samtools -y

    gzip -dr /workspace/ensembl-annotation/Annotating_the_genome/Fastq

  command: |
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba activate annotation

    cd /workspace
    clear

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
